---
- name: Update apt packages
  apt:
    update_cache: yes
  become: yes

- name: Install dependencies for Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  become: yes

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  become: yes

- name: Install Docker Engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes
  become: yes

- name: Ensure Docker service is running and enabled
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes

- name: Enable UFW firewall and set default deny
  ufw:
    state: enabled
    policy: deny
  become: yes

- name: Allow SSH on port 22
  ufw:
    rule: allow
    port: '22'
    proto: tcp
  become: yes
